name: Daily Data Update
on:
schedule:
- cron: "0 3 * * *" # every day at 03:00 UTC
workflow_dispatch:


jobs:
update:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v3
- name: Set up Python
uses: actions/setup-python@v4
with:
python-version: '3.10'
- name: Install deps
run: pip install -r requirements.txt
- name: Run processing
run: python src/data_processing.py
- name: Commit processed
run: |
git config user.name "github-actions"
git config user.email "actions@github.com"
git add data/processed/*
git commit -m "Auto update processed data" || echo "no changes"
git push
